### ISSUE TITLE
How To Use getparty With Username and Password for HTTP File?

### ISSUE THREAD

**Issue by wada3n** [vbauerster/getparty#1]
hello,
how to download files from password protected server file with getparty.
and is there any chance to add ftp support?
thank you

**Comment by vbauerster** [comment]
Hi! You can't, because it's not implemented. This could be relatively easy to implement, but I cannot promise when, because I have short time.
Regarding ftp support.
Chances to add ftp support from my side are very low, unless somebody will make a PR.
`getparty` was written for self-educational purposes, so don't expect active development here.

**Comment by vbauerster** [comment]
basic http auth option has been added.
